services:
  pgdatabase:
    image: postgres:13
    hostname: my_host
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bikes
    volumes:
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./db/ddl.sql:./ddl.sql
      - ./db/data/:/var/lib/postgresql/data/
    ports:
      - "54321:5432"
    restart: unless-stopped
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - "8080:80"